name: rtd-ect
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python >=3.8
  # Required
  - aiohttp >= 3.6
  - cartopy
  - cftime
  - dask
  - geopandas
  - lxml >= 4.5
  - matplotlib-base
  - nest-asyncio >= 1.3
  - numcodecs
  - numpy
  - pandas
  - pydap >= 3.4
  - pyproj
  - python-dateutil
  - rioxarray
  - shapely
  - six
  - xarray
  - xcube >= 1.4.0
  - xvec
  # For Jupyterlab
  - jupyterlab
  - jupyterlab-geojson
  # RTD specials
  - pip:
      - sphinx
      - sphinx_rtd_theme
      - sphinx-argparse
      - sphinx-autodoc-annotation
      - recommonmark
      - mock
      - nbsphinx
